const selectedProjectActionTypes = {
  SET_SELECTED_PROJECT_DEFAULT: "SET_CURRENT_PROJECT_DEFAULT",
  SET_SELECTED_PROJECT_FOUNDATION: "SET_SELECTED_PROJECT_FOUNDATION",
  SET_SELECTED_PROJECT_FINISH: "SET_SELECTED_PROJECT_FINISH",
};

export default selectedProjectActionTypes;
